apiVersion: apps/v1
kind: Deployment
metadata:
  name: dante-proxy
  namespace: media-download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dante-proxy
  template:
    metadata:
      labels:
        app: dante-proxy
    spec:
      hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 100.100.100.100
          - 212.230.135.1
          - 212.230.135.2
        searches:
          - salmon-halfmoon.ts.net
      nodeSelector:
        disk: kostyan-media
      containers:
      - name: dante
        image: yvchenko/dante-proxy:latest
  strategy:
    type: Recreate