apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: sandbox
spec:
  schedule: "56 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            disk: nat-media
          initContainers:
          - name: mongodump
            image: mongo:8.0.20
            command: ["sh", "/scripts/mongo-backup.sh"]
            volumeMounts:
            - name: backups
              mountPath: /backups
          containers:
          - name: rclone-sync
            image: rclone/rclone:latest
            command: ["sh", "/scripts/rclone-sync.sh"]
            volumeMounts:
            - name: backups
              mountPath: /backups
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              subPath: rclone.conf
              readOnly: true
          volumes:
          - name: backups
            hostPath:
              path: /opt/backups
          - name: rclone-config
            hostPath:
              path: /opt/rclone/rclone.conf