apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: sandbox
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            disk: nat-media
          initContainers:
          - name: mongodump
            image: mongo:8.0.20
            command: ["sh", "/scripts/mongo-backup.sh"]
            volumeMounts:
            - name: backups
              mountPath: /backups
            - name: scripts
              mountPath: /scripts
          containers:
          - name: rclone-sync
            image: rclone/rclone:latest
            command: ["sh", "/scripts/rclone-sync.sh"]
            volumeMounts:
              - name: backups
                mountPath: /backups
              - name: rclone-config
                mountPath: /config/rclone/rclone.conf
              - name: scripts
                mountPath: /scripts
          volumes:
          - name: backups
            hostPath:
              path: /opt/backups
          - name: rclone-config
            hostPath:
              path: /opt/rclone/rclone.conf
          - name: scripts
            configMap:
              name: mongo-backup-scripts
              defaultMode: 0755