apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        disk: nat-media
      containers:
      - name: mongodb
        image: mongo:8.0.20
        command: ["mongod", "--noauth"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: db
          mountPath: /data/db
      volumes:
      - name: db
        hostPath:
          path: /opt/appdata/librechat/db
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sandbox
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017