logoutput: stderr

internal: tailscale0 port=1080
external: enp2s0

socksmethod: none
clientmethod: none

user.privileged: root
user.unprivileged: nobody

client pass {
    from: 100.64.0.0/10 to: 0.0.0.0/0
    log: error connect disconnect
}

socks pass {
    from: 100.64.0.0/10 to: 0.0.0.0/0
    protocol: tcp udp
    log: error connect disconnect
}