services:
  dante:
    build:
      context: .
      args:
        DANTE_VERSION: ${DANTE_VERSION}
    container_name: dante-proxy
    network_mode: host
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./danted.conf:/etc/danted.conf:ro