apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      nodeSelector:
        disk: nat-media
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.35.1
        env:
        - name: MEILI_HOST
          value: http://meilisearch:7700
        - name: MEILI_NO_ANALYTICS
          value: "true"
        envFrom:
        - secretRef:
            name: librechat-secrets
        ports:
        - containerPort: 7700
        volumeMounts:
        - name: data
          mountPath: /meili_data
      volumes:
      - name: data
        hostPath:
          path: /opt/appdata/librechat/meili_data
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: sandbox
spec:
  selector:
    app: meilisearch
  ports:
  - port: 7700
    targetPort: 7700