services:
  kavita:
    image: jvmilazz0/kavita:0.9.0
    container_name: kavita
    restart: unless-stopped
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/kavita:/kavita/config
      - /mnt/media/books:/media/books
      - /mnt/media/manga:/media/manga
      - /mnt/media/danmei:/media/danmei
      - /mnt/media/ranobe:/media/ranobe
      - /mnt/media/comics:/media/comics
    ports:
      - 5000:5000
    networks:
      - manga

networks:
  manga:
    name: manga
    driver: bridge