services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/media:/media
    ports:
      - 7878:7878
    networks:
      - arr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    networks:
      - arr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - arr

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      - arr

networks:
  arr:
    driver: bridge