services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/media:/media
    ports:
      - 7878:7878
    networks:
      - media_download

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    networks:
      - media_download

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/prowlarr:/config
      - ../audiobooks/prowlarr-custom/audiobookbay.yml:/config/Definitions/Custom/audiobookbay.yml:ro
    ports:
      - 9696:9696
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - media_download

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - /opt/appdata/bazarr:/config
      - /mnt/media:/media
    ports:
      - 6767:6767
    networks:
      - media_download

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Kiev
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - media_download

  dante:
    build:
      context: dante
      args:
        DANTE_VERSION: ${DANTE_VERSION}
    container_name: dante-proxy
    network_mode: host
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./dante/danted.conf:/etc/danted.conf:ro

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - WEBUI_PORT=8080
    volumes:
      - /mnt/media:/media
      - /opt/appdata/qbittorrent:/config

networks:
  media_download:
    name: media_download
    driver: bridge