services:
  jellyfin:
    environment:
      - JELLYFIN_PublishedServerUrl=http://kostyan-server.salmon-halfmoon.ts.net:8096
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "109"
      - "44"