resources:
  - ../../base
nameSuffix: "-nat"
patches:
  - target:
      kind: Deployment
      name: jellyfin
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          disk: nat-media
      - op: add
        path: /spec/template/spec/runtimeClassName
        value: nvidia
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: JELLYFIN_PublishedServerUrl
            value: http://nat-server.salmon-halfmoon.ts.net:8096
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            nvidia.com/gpu: 1
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: dri
          mountPath: /dev/dri
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: dri
          hostPath:
            path: /dev/dri