Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    Option         "AllowEmptyInitialConfiguration" "true"
    Option         "ConnectedMonitor"    "DFP-0"
    Option         "UseDisplayDevice"    "DFP-0"
    Option         "ModeValidation"      "AllowNonEdidModes, NoMaxPClkCheck, NoDFPNativeResolutionCheck, NoVirtualSizeCheck"
    Option         "MetaModes"           "DFP-0: 1920x1080_60 +0+0"
EndSection