Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    Option         "AllowEmptyInitialConfiguration" "true"
    Option         "ConnectedMonitor"    "DFP-0"
    Option         "MetaModes"           "1920x1080_60 +0+0"
    Option         "UseDisplayDevice"    "DFP-0"
EndSection